version: "3.8"
services:
  consumer:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: consumer
    networks:
      - iotcontrolservice-network
    depends_on:
      - rabbitmq
    command: python -u ./app/main.py
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - 5672:5672
    networks:
      - iotcontrolservice-network
networks:
  iotcontrolservice-network:
    external: true
